version: 2
updates:
  # Schedule for checking updates
  schedule:
    interval: daily

  # CSS dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "css"
    allowed-updates:
      - match:
          update-type: "all"

  # JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "javascript"
    allowed-updates:
      - match:
          update-type: "all"

  # Other dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "other"
    allowed-updates:
      - match:
          update-type: "all"
