# This is an example config file for FMD Server

# Listening precedence: socket > HTTPS > HTTP

# Path to listening UNIX socket. If empty, no unix sockets will be used.
UnixSocketPath: "" # /tmp/fmd.sock
# Permissions to set on the socket after it is created. If < 0, no
# modifications are made. This considered insecure practice, if you
# do it, consider setting a umask for the daemon user before starting it.
# Must start with a leading 0.
UnixSocketChmod: 0660

# The ports FMD Server should listen on
PortSecure: 8443
PortInsecure: 8080

# The length for the user IDs that are generated
UserIdLength: 5

# How many location points or pictures FMD Server should save per account
MaxSavedLoc: 1000
MaxSavedPic: 10

# If RegistrationToken is non-empty, FMD Server will require the FMD app to provide this token during registration.
# Set this to a long random string if you want your instance to be private and not open to registrations by anyone.
# You can e.g. generate a 32 character string with your password manager.
RegistrationToken: ""

# Paths to the server cert and private key (for letting Go terminate TLS)
ServerCrt: "" # /path/to/fullchain.pem
ServerKey: "" # /path/to/privkey.pem
