version: '3.4'

services:

  app:
    image: stormworks/feedropolis
    ports:
      - 80:3000
    user: root
    command: npm run start
    entrypoint: '/app/docker-entrypoint.sh'
    environment:
      - DATABASE_URL=postgres://test:test@db:5432/test
      - BASE_URL=http://localhost
      - DEBUG=

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
