name: Docker Code Quality

on:
  pull_request:
    paths:
    - '.docker/**'
  # Allow manual triggering
  workflow_dispatch:
  # Allow other workflows (e.g. Publish) to invoke this one.
  workflow_call:


permissions:
  contents: read


jobs:
  check:
    name: Check Docker image ${{ matrix.image.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
        - name: app
          dockerfile: ./.docker/app/Dockerfile
        - name: web-nginx
          dockerfile: ./.docker/web-nginx/Dockerfile

    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Validate configuration
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ matrix.image.dockerfile }}
        call: check
