name: Publish

on:
  push:
    branches: [main]
    paths-ignore:
    - '.devcontainer/**'
    - '.github/**'
    - '.vscode/**'
    - 'tests/**'
    - '.*'
    - '*.*-dist'
    - '*.js'
    - '*.json'
    - '*.lock'
    - '*.md'
    - '*.neon'
    - '*.xml'
  # Allow manual triggering
  workflow_dispatch:


permissions:
  contents: read


jobs:
  css-lint:
    uses: ./.github/workflows/css-lint.yml

  docker-code-quality:
    uses: ./.github/workflows/docker-code-quality.yml

  javascript-code-quality:
    uses: ./.github/workflows/javascript-code-quality.yml

  php-code-quality:
    uses: ./.github/workflows/php-code-quality.yml

  shell-code-quality:
    uses: ./.github/workflows/shell-code-quality.yml

  publish:
    name: Publish Docker image ${{ matrix.image.name }}
    needs:
    - css-lint
    - docker-code-quality
    - javascript-code-quality
    - php-code-quality
    - shell-code-quality
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
        - name: app
          dockerfile: ./.docker/app/Dockerfile
          repository_dockerhub: supahgreg/tt-rss
          repository_ghcr: ghcr.io/tt-rss/tt-rss
        - name: web-nginx
          dockerfile: ./.docker/web-nginx/Dockerfile
          repository_dockerhub: supahgreg/tt-rss-web-nginx
          repository_ghcr: ghcr.io/tt-rss/tt-rss-web-nginx

    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Get commit timestamp
      run: |
        COMMIT_TIMESTAMP="$(git show -s --format=%cI HEAD)"
        echo "COMMIT_TIMESTAMP=$COMMIT_TIMESTAMP" >> "$GITHUB_ENV"

    - name: Get commit short SHA
      run: |
        COMMIT_SHORT_SHA="$(git rev-parse --short=8 HEAD)"
        echo "COMMIT_SHORT_SHA=$COMMIT_SHORT_SHA" >> "$GITHUB_ENV"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ matrix.image.repository_dockerhub }}
          ${{ matrix.image.repository_ghcr }}
        tags: |
          # update 'latest'
          type=raw,value=latest
          # short SHA with a 'sha-' prefix (e.g. sha-abc123)
          type=sha
          # date of the associated commit (e.g. 20251126-133700)
          type=raw,value={{commit_date 'YYYYMMDD-HHmmss'}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push to image registries
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ matrix.image.dockerfile }}
        platforms: linux/arm64,linux/amd64
        cache-from: |
          type=gha,scope=${{ matrix.image.name }}
          type=registry,ref=${{ matrix.image.repository_ghcr }}:cache
        cache-to: |
          type=gha,scope=${{ matrix.image.name }},mode=max
          type=registry,ref=${{ matrix.image.repository_ghcr }}:cache,mode=max
        # TODO: clean up build arg and environment variable naming.
        build-args: |
          CI_COMMIT_BRANCH=${{ github.ref_name }}
          CI_COMMIT_SHA=${{ github.sha }}
          CI_COMMIT_SHORT_SHA=${{ env.COMMIT_SHORT_SHA }}
          CI_COMMIT_TIMESTAMP=${{ env.COMMIT_TIMESTAMP }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: true
        sbom: true
        push: true

  publish-version:
    needs:
    - publish
    uses: ./.github/workflows/publish-version-json.yml
    permissions:
      contents: write
