name: Sync+build+push rainmap-lite

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  get_commits:
    runs-on: ubuntu-latest
    # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
    outputs:
      LOCAL_ORIGINAL: ${{ steps.commits.outputs.SETLOCAL_ORIGINAL }}
      REMOTE_ORIGINAL: ${{ steps.commits.outputs.SETREMOTE_ORIGINAL }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'rainmap-lite' # branch
      #- name: set local and remote latest commit as environment variables
      #  id: commits
      #  # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
      #  run: |
      #    echo "::set-output name=SETREMOTE_ORIGINAL::$(git ls-remote https://github.com/cldrn/rainmap-lite HEAD | awk '{ print $1 }')"
      #    echo "::set-output name=SETLOCAL_ORIGINAL::$(cat last_sync_with_original_repo_commit_id_original)"
      - name: set local and remote latest commit as environment variables
        id: commits
        # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
        run: |
          echo "SETREMOTE_ORIGINAL=$(git ls-remote https://github.com/cldrn/rainmap-lite HEAD | awk '{ print $1 }')" >> $GITHUB_OUTPUT
          echo "SETLOCAL_ORIGINAL=$(cat last_sync_with_original_repo_commit_id_original)" >> $GITHUB_OUTPUT

  repo_sync:
    needs: [get_commits]
    runs-on: ubuntu-latest
    # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
    #if: needs.get_commits.outputs.LOCAL_ORIGINAL != needs.get_commits.outputs.REMOTE_ORIGINAL
    steps:
      - name: repo-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/cldrn/rainmap-lite"
          source_branch: "master"
          destination_repo: "git@github.com:schklom/Mirror-workflows.git"
          destination_branch: "rainmap-lite"
          ssh_private_key: ${{ secrets.GITSYNCACTION }}
        # uses: repo-sync/github-sync@v2
        # with:
          # source_repo: "https://github.com/hkalexling/Wikiless.git"
          # source_branch: "master"
          # destination_branch: "Wikiless"
          # github_token: ${{ secrets.REPO_SYNC_GITHUB_SYNC_PERSONAL_ACCESS_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'rainmap-lite' # branch
      
      - name: get most recent commit id on original repo, for next comparison on sync
        if: needs.get_commits.outputs.LOCAL_ORIGINAL != needs.get_commits.outputs.REMOTE_ORIGINAL
        run: git ls-remote https://github.com/cldrn/rainmap-lite HEAD | awk '{ print $1 }' > last_sync_with_original_repo_commit_id_original
      
      - name: Commit and push the change
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Add last_sync_with_original_repo_commit_id_original
      
      # - name: Checkout to add run.bash to the repo, from my repo
        # #run: git clone -b rainmap-lite-docker --single-branch https://github.com/schklom/Mirror-workflows rainmap-lite-docker
        # run: wget https://raw.githubusercontent.com/schklom/Mirror-workflows/rainmap-lite-docker/run.bash
      
      # - name: Commit and push run.bash
        # uses: stefanzweifel/git-auto-commit-action@v4.16.0
        # with:
          # commit_message: Add run.bash

  build_push:
    needs: [repo_sync]
    #if: ${{ false }}
    #needs: [get_commits]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          #repository: 'schklom/aaa'
          ref: 'rainmap-lite-docker' # branch
      
      # https://github.com/docker/setup-qemu-action#usage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
        #with:
          #image: tonistiigi/binfmt:latest
          #platforms: all
          #platforms: arm/v7
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0
        #with:
          #install: true
      #- name: Available platforms
      #  run: echo ${{ steps.buildx.outputs.platforms }}
      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://github.com/docker/build-push-action#multi-platform-image
      - name: Build and push rainmap-lite-docker
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          file: Dockerfile
          #platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
          #platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          platforms: linux/arm64
          pull: true
          push: true
          tags: |
            schklom/rainmap-lite:latest
