name: Sync+build+push SimplyTranslate

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  get_commits:
    #if: false
    runs-on: ubuntu-latest
    # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
    outputs:
      LOCAL_ENGINES: ${{ steps.commits.outputs.SETLOCAL_ENGINES }}
      REMOTE_ENGINES: ${{ steps.commits.outputs.SETREMOTE_ENGINES }}
      LOCAL_WEB: ${{ steps.commits.outputs.SETLOCAL_WEB }}
      REMOTE_WEB: ${{ steps.commits.outputs.SETREMOTE_WEB }}
      LOCAL_DOCKER: ${{ steps.commits.outputs.SETLOCAL_DOCKER }}
      REMOTE_DOCKER: ${{ steps.commits.outputs.SETREMOTE_DOCKER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'SimplyTranslate' # branch
      - name: set local and remote latest commit as environment variables
        id: commits        
        # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
        # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
        run: |
          echo "SETREMOTE_ENGINES=$(git ls-remote https://codeberg.org/SimpleWeb/SimplyTranslate-Engines HEAD | awk '{ print $1 }')" >> $GITHUB_OUTPUT
          echo "SETLOCAL_ENGINES=$(cat last_sync_with_original_repo_commit_id_engines)" >> $GITHUB_OUTPUT
          echo "SETREMOTE_WEB=$(git ls-remote https://codeberg.org/SimpleWeb/SimplyTranslate-Web HEAD | awk '{ print $1 }')" >> $GITHUB_OUTPUT
          echo "SETLOCAL_WEB=$(cat last_sync_with_original_repo_commit_id_web)" >> $GITHUB_OUTPUT
          echo "SETREMOTE_DOCKER=$(git ls-remote https://codeberg.org/SimpleWeb/SimplyTranslate-Docker HEAD | awk '{ print $1 }')" >> $GITHUB_OUTPUT
          echo "SETLOCAL_DOCKER=$(cat last_sync_with_original_repo_commit_id_docker)" >> $GITHUB_OUTPUT
  
  repo_sync:
    needs: [get_commits]
    runs-on: ubuntu-latest
    # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
    #if: false
    if: needs.get_commits.outputs.LOCAL_ENGINES != needs.get_commits.outputs.REMOTE_ENGINES || needs.get_commits.outputs.LOCAL_WEB != needs.get_commits.outputs.REMOTE_WEB || needs.get_commits.outputs.LOCAL_DOCKER != needs.get_commits.outputs.REMOTE_DOCKER
    steps:
      - name: repo-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://codeberg.org/SimpleWeb/SimplyTranslate-Docker"
          source_branch: "master"
          destination_repo: "git@github.com:schklom/Mirror-workflows.git"
          destination_branch: "SimplyTranslate"
          ssh_private_key: ${{ secrets.GITSYNCACTION }}
        # uses: repo-sync/github-sync@v2
        # with:
          # source_repo: "https://github.com/hkalexling/Mango.git"
          # source_branch: "master"
          # destination_branch: "SimplyTranslate"
          # github_token: ${{ secrets.REPO_SYNC_GITHUB_SYNC_PERSONAL_ACCESS_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'SimplyTranslate' # branch
      - name: get most recent commit id on original repo, for next comparison on sync PART 1
        run: git ls-remote https://codeberg.org/SimpleWeb/SimplyTranslate-Engines HEAD | awk '{ print $1 }' > last_sync_with_original_repo_commit_id_engines
      - name: get most recent commit id on original repo, for next comparison on sync PART 2
        run: git ls-remote https://codeberg.org/SimpleWeb/SimplyTranslate-Web HEAD | awk '{ print $1 }' > last_sync_with_original_repo_commit_id_web
      - name: get most recent commit id on original repo, for next comparison on sync PART 3
        run: git ls-remote https://codeberg.org/SimpleWeb/SimplyTranslate-Docker HEAD | awk '{ print $1 }' > last_sync_with_original_repo_commit_id_docker

      - name: Commit and push the change
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Add last_sync_with_original_repo_commit_id_engines + last_sync_with_original_repo_commit_id_web + last_sync_with_original_repo_commit_id_docker + Fix Dockerfile

  build_push:
    needs: [repo_sync]
    #needs: [get_commits]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          #repository: 'schklom/SimplyTranslate'
          ref: 'SimplyTranslate' # branch
      # https://github.com/docker/setup-qemu-action#usage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
        #with:
          #image: tonistiigi/binfmt:latest
          #platforms: all
          #platforms: arm/v7
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.10.0
        #with:
          #install: true
      #- name: Available platforms
      #  run: echo ${{ steps.buildx.outputs.platforms }}
      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://github.com/docker/build-push-action#multi-platform-image
      - name: Build and push SimplyTranslate
        uses: docker/build-push-action@v4.2.1
        with:
          context: web
          file: ./web/Dockerfile
          #platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |
            schklom/simplytranslate:latest
